import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from firebase_config import get_firebase_ref
from SP_utils import sanitize_key
from Home import check_participant

# ================================
# Configuration
# ================================

# Experiment numbers mapping
EXPERIMENTS = {
    'MDD': {
        'gptsmall_basic': [(6201, 1111), (6201, 1112)],
        'gptsmall_guided': [(6201, 2111), (6201, 2112)],
        'gptlarge_guided': [(6201, 1121), (6201, 1122)],
        'claudesmall_basic': [(6201, 1131), (6201, 1132)],
        'claudesmall_guided': [(6201, 2131), (6201, 2132)],
        'claudelarge_guided': [(6201, 1141), (6201, 1142)],
    },
    'BD': {
        'gptsmall_basic': [(6202, 1211), (6202, 1212)],
        'gptsmall_guided': [(6202, 2211), (6202, 2212)],
        'gptlarge_guided': [(6202, 1221), (6202, 1222)],
        'claudesmall_basic': [(6202, 1231), (6202, 1232)],
        'claudesmall_guided': [(6202, 2231), (6202, 2232)],
        'claudelarge_guided': [(6202, 1241), (6202, 1242)],
    },
    'OCD': {
        'gptsmall_basic': [(6206, 1611), (6206, 1612)],
        'gptsmall_guided': [(6206, 2611), (6206, 2612)],
        'gptlarge_guided': [(6206, 1621), (6206, 1622)],
        'claudesmall_basic': [(6206, 1631), (6206, 1632)],
        'claudesmall_guided': [(6206, 2631), (6206, 2632)],
        'claudelarge_guided': [(6206, 1641), (6206, 1642)],
    }
}

# Color mapping for disorders
DISORDER_COLORS = {
    'MDD': '#E63946',  # Dark Red
    'BD': '#06D6A0',   # Dark Teal
    'OCD': '#FFB703',  # Dark Orange/Yellow
}

# Marker shapes and fill styles for models
MARKER_CONFIG = {
    'gptsmall_basic': {'marker': 'o', 'fill': 'empty'},      # Empty circle
    'gptsmall_guided': {'marker': 'o', 'fill': 'filled'},    # Filled circle
    'gptlarge_guided': {'marker': 'o', 'fill': 'hatched'},   # Hatched circle
    'claudesmall_basic': {'marker': 's', 'fill': 'empty'},   # Empty square
    'claudesmall_guided': {'marker': 's', 'fill': 'filled'}, # Filled square
    'claudelarge_guided': {'marker': 's', 'fill': 'hatched'}, # Hatched square
}

# Model display names
MODEL_NAMES = {
    'gptsmall_basic': 'GPT-Small + Basic',
    'gptsmall_guided': 'GPT-Small + Guided',
    'gptlarge_guided': 'GPT-Large + Guided',
    'claudesmall_basic': 'Claude-Small + Basic',
    'claudesmall_guided': 'Claude-Small + Guided',
    'claudelarge_guided': 'Claude-Large + Guided',
}


# ================================
# Data Loading Functions
# ================================

def load_psyche_scores(firebase_ref):
    """Load PSYCHE scores from Firebase for all experiments
    
    PSYCHE scores are generated by the Evaluation page (연구자용 격리 폴더) 
    and saved with key pattern: clients_{client_number}_psyche_{diagnosis}_{model}_{exp_number}
    at the root level of Firebase (not nested under clients/)
    """
    scores_data = []
    
    # Get all data from Firebase root
    try:
        all_data = firebase_ref.get()
        if not all_data:
            return scores_data
        
        # Search through all keys for psyche evaluation data
        for key in all_data.keys():
            # Key format: clients_{client_number}_psyche_{diagnosis}_{model}_{exp_number}
            if "_psyche_" in key and key.startswith("clients_"):
                # Parse the key
                parts = key.split("_")
                # Expected: ['clients', '{client_num}', 'psyche', '{diagnosis}', '{model}', '{exp_num}']
                if len(parts) >= 6 and parts[2] == "psyche":
                    client_num = int(parts[1])
                    exp_num = int(parts[5])
                    
                    # Find which disorder and model_type this exp_num belongs to
                    # exp_num is unique, so we can just search for it
                    found = False
                    for diagnosis, models in EXPERIMENTS.items():
                        for model_type, exp_list in models.items():
                            if (client_num, exp_num) in exp_list:
                                found = True
                                break
                        if found:
                            break
                    
                    if found:
                            # Load the data
                            data = firebase_ref.child(key).get()
                            if data and 'psyche_score' in data:
                                scores_data.append({
                                    'disorder': diagnosis,
                                    'model': model_type,
                                    'client_num': client_num,
                                    'exp_num': exp_num,
                                    'psyche_score': data['psyche_score']
                                })
    
    except Exception as e:
        st.error(f"Error loading PSYCHE scores: {e}")
        import traceback
        st.code(traceback.format_exc())
    
    return scores_data


# ================================
# Plotting Function
# ================================

def create_psyche_plot(scores_data):
    """Create a matplotlib scatter plot on a single axis (PSYCHE score)"""
    
    fig, ax = plt.subplots(figsize=(14, 8), facecolor='black')
    ax.set_facecolor('black')
    
    # Track which models have been added to legend
    added_models = set()
    
    # Plot each disorder-model combination
    for disorder in ['MDD', 'BD', 'OCD']:
        for model_type in ['gptsmall_basic', 'gptsmall_guided', 'gptlarge_guided', 
                           'claudesmall_basic', 'claudesmall_guided', 'claudelarge_guided']:
            # Filter data
            filtered = [s for s in scores_data 
                       if s['disorder'] == disorder and s['model'] == model_type]
            
            if not filtered:
                continue
            
            # Extract scores
            scores = [s['psyche_score'] for s in filtered]
            
            # Y-axis with small jitter to avoid overlap
            y_values = [0 + np.random.uniform(-0.15, 0.15) for _ in scores]
            
            # Only add to legend once per model (first disorder)
            label = MODEL_NAMES[model_type] if model_type not in added_models else None
            if label:
                added_models.add(model_type)
            
            # Get marker configuration
            config = MARKER_CONFIG[model_type]
            marker = config['marker']
            fill_style = config['fill']
            
            # Set fill properties based on style
            if fill_style == 'empty':
                # Empty marker - no fill, just edge
                facecolor = 'none'
                edgecolor = DISORDER_COLORS[disorder]
                hatch = None
                alpha = 1.0
            elif fill_style == 'filled':
                # Filled marker
                facecolor = DISORDER_COLORS[disorder]
                edgecolor = 'white'
                hatch = None
                alpha = 0.9
            else:  # hatched
                # Hatched marker
                facecolor = DISORDER_COLORS[disorder]
                edgecolor = 'white'
                hatch = '///'
                alpha = 0.7
            
            # Plot
            ax.scatter(
                scores,
                y_values,
                marker=marker,
                s=300,  # size
                facecolors=facecolor,
                edgecolors=edgecolor,
                linewidths=2.5,
                hatch=hatch,
                alpha=alpha,
                label=label
            )
    
    # Styling
    ax.set_xlabel('PSYCHE Score', fontsize=14, fontweight='bold', color='white')
    ax.set_title('PACA Performance: PSYCHE Scores by Disorder and Model', 
                 fontsize=16, fontweight='bold', pad=20, color='white')
    
    # Remove y-axis
    ax.set_yticks([])
    ax.set_ylabel('')
    
    # Grid
    ax.grid(True, axis='x', alpha=0.2, linestyle='--', color='gray')
    ax.set_ylim(-0.5, 0.5)
    
    # Set x-axis range and styling
    if scores_data:
        max_score = max([s['psyche_score'] for s in scores_data])
        ax.set_xlim(0, max(max_score * 1.1, 55))  # At least show full range to max possible (55)
    else:
        ax.set_xlim(0, 55)  # Max possible PSYCHE score
    
    ax.tick_params(colors='white', labelsize=11)
    
    # Simplified legend for models
    legend1 = ax.legend(title='Models', title_fontsize=11, fontsize=10,
                       loc='upper left', frameon=True, facecolor='#1a1a1a',
                       edgecolor='white', labelcolor='white')
    legend1.get_title().set_color('white')
    
    # Add color legend for disorders manually
    from matplotlib.patches import Patch
    disorder_patches = [Patch(facecolor=DISORDER_COLORS['MDD'], label='MDD'),
                       Patch(facecolor=DISORDER_COLORS['BD'], label='BD'),
                       Patch(facecolor=DISORDER_COLORS['OCD'], label='OCD')]
    legend2 = ax.legend(handles=disorder_patches, title='Disorders', title_fontsize=11, fontsize=10,
                       loc='lower left', frameon=True, facecolor='#1a1a1a',
                       edgecolor='white', labelcolor='white')
    legend2.get_title().set_color('white')
    
    # Add first legend back (matplotlib removes previous legend when adding new one)
    ax.add_artist(legend1)
    
    # Remove spines
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_visible(False)
    ax.spines['bottom'].set_color('white')
    
    plt.tight_layout()
    
    return fig


# ================================
# Main Page
# ================================

def main():
    st.set_page_config(
        page_title="PSYCHE Score Plot",
        page_icon="📊",
        layout="wide"
    )
    
    # Check authentication
    if not check_participant():
        st.stop()
    
    # Firebase connection
    firebase_ref = get_firebase_ref()
    if firebase_ref is None:
        st.error("Firebase 초기화 실패")
        st.stop()
    
    # Page Header
    st.title("📊 PACA Performance Visualization")
    st.markdown("---")
    
    # Info box
    with st.expander("ℹ️ 그래프 설명", expanded=True):
        st.markdown("""
        이 그래프는 **PACA(Psychiatric Assessment Conversational Agent)**의 성능을 
        **PSYCHE Score**로 시각화한 것입니다.
        
        ### 구성 요소:
        
        **색상 (질환)**:
        - 🔴 **빨강**: Major Depressive Disorder (MDD)
        - 🔵 **청록색**: Bipolar Disorder (BD)
        - 🟡 **노랑**: Obsessive-Compulsive Disorder (OCD)
        
        **모양 및 패턴 (모델)**:
        - **동그라미 (GPT 계열)**:
          - ○ 빈 동그라미: GPT-Small + Basic
          - ● 색칠된 동그라미: GPT-Small + Guided
          - ◐ 빗선 동그라미: GPT-Large + Guided
        - **네모 (Claude 계열)**:
          - □ 빈 네모: Claude-Small + Basic
          - ■ 색칠된 네모: Claude-Small + Guided
          - ▦ 빗선 네모: Claude-Large + Guided
        
        ### PSYCHE Score:
        - X축은 PSYCHE Score (0-55점)를 나타냅니다
        - PSYCHE Score는 **연구자용 Evaluation 페이지**에서 자동 생성됩니다
        - PACA의 construct와 SP(ground truth) construct를 PSYCHE RUBRIC 기준으로 비교 평가
        - 점수가 높을수록 PACA의 성능이 우수함을 의미합니다
        - 각 모델-질환 조합마다 2개의 실험 결과가 표시됩니다
        """)
    
    # Load data
    with st.spinner("데이터를 불러오는 중..."):
        scores_data = load_psyche_scores(firebase_ref)
    
    # Debug: Show available keys if no data found
    if not scores_data:
        with st.expander("🔍 디버깅: Firebase 키 확인", expanded=False):
            try:
                all_data = firebase_ref.get()
                if all_data:
                    psyche_keys = [k for k in all_data.keys() if "_psyche_" in k]
                    if psyche_keys:
                        st.write(f"Found {len(psyche_keys)} PSYCHE evaluation keys:")
                        for key in sorted(psyche_keys):
                            st.code(key)
                    else:
                        st.write("No keys containing '_psyche_' found")
                        st.write("Sample keys from Firebase:")
                        for key in list(all_data.keys())[:10]:
                            st.code(key)
                else:
                    st.write("Firebase returned no data")
            except Exception as e:
                st.error(f"Error fetching keys: {e}")
    
    if not scores_data:
        st.warning("⚠️ 아직 평가된 데이터가 없습니다. 연구자용 격리폴더의 Evaluation 페이지에서 PSYCHE Score를 먼저 생성해주세요.")
        st.stop()
    
    # Display statistics
    st.markdown("### 📈 요약 통계")
    col1, col2, col3, col4 = st.columns(4)
    
    all_scores = [s['psyche_score'] for s in scores_data]
    
    with col1:
        st.metric("검증 완료", f"{len(scores_data)}/36")
    with col2:
        st.metric("평균 점수", f"{sum(all_scores)/len(all_scores):.2f}")
    with col3:
        st.metric("최고 점수", f"{max(all_scores):.2f}")
    with col4:
        st.metric("최저 점수", f"{min(all_scores):.2f}")
    
    st.markdown("---")
    
    # Create and display plot
    fig = create_psyche_plot(scores_data)
    st.pyplot(fig)
    
    # Detailed data table
    st.markdown("---")
    st.markdown("### 📋 상세 데이터")
    
    df = pd.DataFrame(scores_data)
    df['model_name'] = df['model'].map(MODEL_NAMES)
    df = df[['disorder', 'model_name', 'client_num', 'exp_num', 'psyche_score']]
    df.columns = ['질환', '모델', 'Client 번호', 'Exp 번호', 'PSYCHE Score']
    df = df.sort_values(['질환', '모델', 'Client 번호', 'Exp 번호'])
    
    st.dataframe(df, use_container_width=True, hide_index=True)


if __name__ == "__main__":
    main()
